# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore: 
      - '**.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # python3 -m pip install --user pretextbook
      - uses: actions/checkout@v2

      - name: Update System Packages
        run: sudo apt-get update -y

      - name: Install XeLaTeX
        run: sudo apt-get install texlive-xetex

      - name: Install pdf2svg
        run: sudo apt install pdf2svg

      - name: Install PreTeXt
        run: |
          python3 --version
          pip3 --version
          pip3 install --user --upgrade pretext

      - name: Install pdfCropMargins
        run: pip3 install pdfCropMargins

      - name: Install lxml
        run: pip3 install lxml

      - name: Install GhostScript
        run: sudo apt-get -y install ghostscript

      # Runs a single command using the runners shell
      - name: Build Book Assets
        run: pretext generate

      - name: Build Book
        run: pretext build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy HTML to NUL Servers
        run: |
          aws s3 sync ./output/web ${{ secrets.AWS_S3_BUCKET_NAME }} --delete
